# Source: https://github.com/marketplace/actions/php-syntax-checker-lint
name: PHP Linting
on: pull_request
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: StephaneBour/actions-php-lint@7.4
          with: 
            dir: './src'
