# Source: https://github.com/marketplace/actions/php-syntax-checker-lint
# Source: https://github.com/marketplace/actions/php-lint
name: PHP Linting
on: push
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: StephaneBour/actions-php-lint@7.4
          with: 
            dir: './src'
